services:
  # Web Service (Django)
  - type: web
    name: alx-backend-security
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn alx_backend_security.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "2"
